---
title: "COVID-19 WDI Explorer"
author: "Brian Stacy"
date: "4/22/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(skimr)
library(kableExtra)
library(readxl)
library(Hmisc)
library(haven)
library(lubridate)
library(httr)
library(jsonlite)
library(wbstats)
library(broom)
library(ggpmisc)
library(wbggeo)
library(wbgmaps)
library(ggthemes)
library(patchwork)
#pull date
case_date <- "04-27-2020"

# Directory for SPI csv files that were previously created
csv_dir <- "C:/Users/wb469649/Documents/Github/COVID-19/csse_covid_19_data/csse_covid_19_daily_reports/"




```

## R Markdown


Get latest case data
```{r load_cases}

covid_cases_df <- read_csv(paste(csv_dir,case_date,".csv", sep="")) %>%
  group_by(Country_Region) %>% #summarise to country level
  summarise_all((~(if(is.numeric(.)) sum(., na.rm = TRUE) else first(.)))) %>%
  ungroup() %>%
  rename(country=Country_Region) %>%
  mutate(country=case_when(
    country=="US" ~ "United States", 
    country=="Iran" ~ "Iran, Islamic Rep.", 
    country=="Russia" ~ "Russian Federation",
    country=="Egypt" ~ "Egypt, Arab Rep.",
    country=="Venezuela" ~ "Venezuela, RB",
    country=="Burma" ~ "Myanmar",
    country=="Laos" ~ "Lao PDR",
    country=="Czechia" ~ "Czech Republic",
    country=="Slovakia" ~ "Slovak Republic",
    country=="Korea, South" ~ "Korea, Rep.",
    TRUE ~ country
  ))



```

Bring in SDG data from World Bank

```{r wdi}

# make request to World Bank API
wdiRequest <- GET(url = "http://api.worldbank.org/v2/indicator?per_page=20000&format=json&source=2")
wdiResponse <- content(wdiRequest, as = "text", encoding = "UTF-8")

# Parse the JSON content and convert it to a data frame.
wdisJSON <- jsonlite::fromJSON(wdiResponse, flatten = TRUE) %>%
    data.frame()

EdStatsRequest <- GET(url = "http://api.worldbank.org/v2/indicator?per_page=20000&format=json&source=12")
EdStatsResponse <- content(EdStatsRequest, as = "text", encoding = "UTF-8")

# Parse the JSON content and convert it to a data frame.
EdStatsJSON <- jsonlite::fromJSON(EdStatsResponse, flatten = TRUE) %>%
  data.frame()

aki<- c('Poverty headcount ratio at $1.90 a day (2011 PPP) (% of population)',
        'Prevalence of stunting, height for age (% of children under 5)',
        'Mortality rate, under-5 (per 1,000 live births)', 
        'Pupils below minimum reading proficiency at end of primary (%). Low GAML threshold',
        'People using safely managed drinking water services (% of population)',
        'Access to electricity (% of population)',
        'Unemployment, total (% of total labor force) (national estimate)' ,
        'Manufacturing, value added (% of GDP)',
        'Annualized average growth rate in per capita real survey mean consumption or income, bottom 40% of population (%)',
        'Level of water stress: freshwater withdrawal as a proportion of available freshwater resources',
        'Renewable energy consumption (% of total final energy consumption)',
        'Total greenhouse gas emissions (kt of CO2 equivalent)',
        'Terrestrial and marine protected areas (% of total territorial area)',
        'Households and NPISHs Final consumption expenditure (current LCU)',
        'GNI (current LCU)',
        'Debt service (PPG and IMF only, % of exports of goods, services and primary income)'  )

get_tag_aki_df<-wdisJSON %>%
  bind_rows(EdStatsJSON) %>%
  filter((name %in% aki	)) %>%
  group_by(id) %>%
  summarise_all(~first(.)) %>%
  arrange(factor(name, levels = aki)) %>%
  select(id, name,  sourceOrganization) 


cache_list<-wbstats::wbcache()

aki_list<-get_tag_aki_df[,'id']

sdg_df<-  wbstats::wb(country="countries_only", 
              indicator=aki_list$id,
              cache=cache_list,
              startdate=2010,
              enddate=2019,
              return_wide = F, removeNA=T) %>%
  group_by(country, iso2c, indicator, indicatorID) %>%
  arrange(date) %>%
  summarise(value=last(na.omit(value))) # keep just last year of data for country



all_df<-  wbstats::wb(country="countries_only", 
              indicator=wdisJSON$id,
              cache=cache_list,
              startdate=2010,
              enddate=2019,
              return_wide = F, removeNA=T) %>%
  group_by(country, iso2c, indicator, indicatorID) %>%
  arrange(date) %>%
  summarise(value=last(na.omit(value))) # keep just last year of data for country

```

Link Case data with SDG data

```{r link_data}

combined_df <- covid_cases_df %>%
  left_join(sdg_df)

all_df <- covid_cases_df %>%
  left_join(all_df)
```

# Plots

```{r covid_plots}

Confirmed_plot <- ggplot(data=combined_df, aes(x=value, y=log(Confirmed), group=indicator)) +
  geom_point() +
  geom_smooth() +
  facet_wrap(~indicator, scales = 'free') +
  theme_bw()

  Confirmed_plot

  
Death_plot <- ggplot(data=combined_df, aes(x=value, y=log(Deaths), group=indicator)) +
  geom_point() +
  geom_smooth() +
  facet_wrap(~indicator, scales = 'free') +
  theme_bw()

  Death_plot
  
  
```

Now do seperate regressions for each covariate to see which predicts best.

```{r regressions}

#create nested database
nested <- all_df %>%
  select(indicator, indicatorID, country, iso2c, Confirmed, Deaths, value) %>%
  group_by(indicator, indicatorID) %>%
  nest(data=c(country, iso2c, Confirmed, Deaths, value)) %>%
  filter(!is.na(indicator))

#regress each indicator on cases and deaths
cases <- nested %>%
  mutate(
    case_regs = map(data, ~lm(Confirmed~value, data=.x)), #do regressions
    case_tidied=map(case_regs,glance), #now tidy up results to show r^2
  ) %>%
  unnest(case_tidied) %>%
  select(-data,-case_regs) %>%
  mutate(r.squared=round(r.squared,3))

deaths <- nested %>%
  mutate(
    death_regs = map(data, ~lm(Deaths~value, data=.x)), #do regressions
    death_tidied=map(death_regs,glance), #now tidy up results to show r^2
  ) %>%
  unnest(death_tidied) %>%
  select(-data,-death_regs) %>%
  mutate(r.squared=round(r.squared,3))


```


```{r more_plots}

#High R^2 indicators
# Arms exports (SIPRI trend indicator values)	MS.MIL.XPRT.KD
# External debt stocks, private nonguaranteed (PNG) (DOD, current US$)	DT.DOD.DPNG.CD
# Debt service on external debt, total (TDS, current US$)	DT.TDS.DECT.CD
# International tourism, number of arrivals	ST.INT.ARVL

graph_indicators <- c( 'ST.INT.ARVL')

graph_df<-  wbstats::wb(country="countries_only", 
              indicator=graph_indicators,
              cache=cache_list,
              startdate=2010,
              enddate=2019,
              return_wide = F, removeNA=F) %>%
  group_by(country, iso2c, indicator, indicatorID) %>%
  arrange(date) %>%
  summarise(value=last(na.omit(value))) %>% # keep just last year of data for country
  left_join(covid_cases_df)


Confirmed_plot_travel <- ggplot(data=graph_df, aes(x=log(value), y=log(Confirmed), group=indicator)) +
  geom_point() +
  geom_text(aes(label=country), position=position_jitter(width=1,height=1), check_overlap=T) +
  geom_smooth(method='lm') +
  theme_bw() + 
  labs(
    title='Plot of Log Confirmed Cases on Log International tourism, number of arrivals',
    caption='Source: Covid-19 cases from Johns Hopkins CSSE on April 21,2020.\nInternational Tourism from World Bank WDI: ST.INT.ARVL'
  ) +
  xlab('Log International tourism, number of arrivals') +
  ylab('Log Confirmed Covid-19 Cases') +
  stat_poly_eq(aes(label = paste(..eq.label.., ..rr.label.., sep = "~~~")), 
                     label.x.npc = "right", label.y.npc = 0.1,
                     formula = 'y~x', parse = TRUE, size = 4)

  Confirmed_plot_travel
  
  
  plotly::ggplotly(Confirmed_plot_travel)


```

# Maps

```{r maps}

quality = "low"
maps <- wbgmaps::wbgmaps[[quality]]


country<-wbcountries()
map_df <- graph_df %>%
  left_join(country)

p1<-ggplot() +
  geom_map(data = map_df, aes(map_id = iso3c, fill = log(Confirmed)), map = maps$countries) + 
  geom_polygon(data = maps$disputed, aes(long, lat, group = group, map_id = id), fill = "grey80") + 
  geom_polygon(data = maps$lakes, aes(long, lat, group = group), fill = "white")  +
   geom_path(data = maps$boundaries,
             aes(long, lat, group = group),
             color = "white",
             size = 0.1,
             lineend = maps$boundaries$lineend,
            linetype = maps$boundaries$linetype) +
  scale_x_continuous(expand = c(0, 0), limits = standard_crop_wintri()$xlim) +
  scale_y_continuous(expand = c(0, 0), limits = standard_crop_wintri()$ylim) +
  scale_fill_gradientn(
    name = 'Log Covid-19 Caseload',
    colours = topo.colors(10),
    trans = 'reverse'
  ) +
  coord_equal() +
  theme_map(base_size=12) +
  labs(
    title='Log Covid-19 Caseload',
    caption = 'Source: Covid-19 cases from Johns Hopkins CSSE on April 21,2020.'
  )

p2<-ggplot() +
  geom_map(data = map_df, aes(map_id = iso3c, fill = log(value)), map = maps$countries) + 
  geom_polygon(data = maps$disputed, aes(long, lat, group = group, map_id = id), fill = "grey80") + 
  geom_polygon(data = maps$lakes, aes(long, lat, group = group), fill = "white")  +
   geom_path(data = maps$boundaries,
             aes(long, lat, group = group),
             color = "white",
             size = 0.1,
             lineend = maps$boundaries$lineend,
            linetype = maps$boundaries$linetype) +
  scale_x_continuous(expand = c(0, 0), limits = standard_crop_wintri()$xlim) +
  scale_y_continuous(expand = c(0, 0), limits = standard_crop_wintri()$ylim) +
  scale_fill_gradientn(
    name = 'Log International tourism,\nnumber of arrivals',
    colours = topo.colors(10),
    trans = 'reverse'
  ) +
  coord_equal() +
  theme_map(base_size=12) +
  labs(
    title='Log International tourism,\nnumber of arrivals',
    caption = 'Source: International Tourism from World Bank WDI: ST.INT.ARVL'
  )

p1 / p2

```

